openapi: '3.0.0'
info:
  title: protocol api specification
  description: transaction lifecycle specification
  version: 0.0.0
  contact:
    email: engineering@noshdelivery.io
security:
  - NodeAuth: []
paths:
  /search:
    post:
      $ref: './components/requestBodies/Search.yaml'
  /on_search:
    post:
      $ref: './components/requestBodies/OnSearch.yaml'
  /select:
    post:
      $ref: './components/requestBodies/Select.yaml'
  /on_select:
    post:
      $ref: './components/requestBodies/OnSelect.yaml'
  /init:
    post:
      $ref: './components/requestBodies/Init.yaml'
  /on_init:
    post:
      $ref: './components/requestBodies/OnInit.yaml'
  /status:
    post:
      $ref: './components/requestBodies/Status.yaml'
  /on_status:
    post:
      $ref: './components/requestBodies/OnStatus.yaml'
  /cancel:
    post:
      $ref: './components/requestBodies/Cancel.yaml'
  /on_cancel:
    post:
      $ref: './components/requestBodies/OnCancel.yaml'
components:
  securitySchemes:
    $ref: './components/securitySchemes.yaml'
  schemas:
    $ref: './components/schemas.yaml'
  requestBodies: 
    $ref: './components/requestBodies.yaml'
  responses: 
    $ref: './components/responses.yaml'
  headers:
    $ref: './components/headers.yaml'